### ISSUE TITLE
About the TerraInc dataset

### ISSUE THREAD

**Issue by yuu-Wang** [tangli-udel/DRE#1]
Hello, I was wondering where you found the TerraInc dataset from, as it seems that there is no such dataset with classification available on the internet at the moment. I would really appreciate it if you could let me know, and I am looking forward to your reply. Thank you.

**Comment by tangli-udel** [comment]
Hi,
TerraInc is the abbreviation of the **Terra Incognita** dataset.
Paper link: https://openaccess.thecvf.com/content_ECCV_2018/papers/Beery_Recognition_in_Terra_ECCV_2018_paper.pdf

You can easily get an organized version from the DomainBed repo: https://github.com/facebookresearch/DomainBed
